# coding: utf-8

"""
    Solvice API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.big_decimal import BigDecimal  # noqa: F401,E501
from swagger_client.models.order_windows import OrderWindows  # noqa: F401,E501


class Order(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'location': 'str',
        'duration': 'BigDecimal',
        'demand': 'BigDecimal',
        'demand2': 'BigDecimal',
        'type': 'list[str]',
        'windows': 'list[OrderWindows]'
    }

    attribute_map = {
        'name': 'name',
        'location': 'location',
        'duration': 'duration',
        'demand': 'demand',
        'demand2': 'demand2',
        'type': 'type',
        'windows': 'windows'
    }

    def __init__(self, name=None, location=None, duration=None, demand=None, demand2=None, type=None, windows=None):  # noqa: E501
        """Order - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._location = None
        self._duration = None
        self._demand = None
        self._demand2 = None
        self._type = None
        self._windows = None
        self.discriminator = None
        self.name = name
        self.location = location
        if duration is not None:
            self.duration = duration
        if demand is not None:
            self.demand = demand
        if demand2 is not None:
            self.demand2 = demand2
        if type is not None:
            self.type = type
        if windows is not None:
            self.windows = windows

    @property
    def name(self):
        """Gets the name of this Order.  # noqa: E501


        :return: The name of this Order.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Order.


        :param name: The name of this Order.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def location(self):
        """Gets the location of this Order.  # noqa: E501


        :return: The location of this Order.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this Order.


        :param location: The location of this Order.  # noqa: E501
        :type: str
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501

        self._location = location

    @property
    def duration(self):
        """Gets the duration of this Order.  # noqa: E501


        :return: The duration of this Order.  # noqa: E501
        :rtype: BigDecimal
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this Order.


        :param duration: The duration of this Order.  # noqa: E501
        :type: BigDecimal
        """

        self._duration = duration

    @property
    def demand(self):
        """Gets the demand of this Order.  # noqa: E501


        :return: The demand of this Order.  # noqa: E501
        :rtype: BigDecimal
        """
        return self._demand

    @demand.setter
    def demand(self, demand):
        """Sets the demand of this Order.


        :param demand: The demand of this Order.  # noqa: E501
        :type: BigDecimal
        """

        self._demand = demand

    @property
    def demand2(self):
        """Gets the demand2 of this Order.  # noqa: E501


        :return: The demand2 of this Order.  # noqa: E501
        :rtype: BigDecimal
        """
        return self._demand2

    @demand2.setter
    def demand2(self, demand2):
        """Sets the demand2 of this Order.


        :param demand2: The demand2 of this Order.  # noqa: E501
        :type: BigDecimal
        """

        self._demand2 = demand2

    @property
    def type(self):
        """Gets the type of this Order.  # noqa: E501


        :return: The type of this Order.  # noqa: E501
        :rtype: list[str]
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Order.


        :param type: The type of this Order.  # noqa: E501
        :type: list[str]
        """

        self._type = type

    @property
    def windows(self):
        """Gets the windows of this Order.  # noqa: E501


        :return: The windows of this Order.  # noqa: E501
        :rtype: list[OrderWindows]
        """
        return self._windows

    @windows.setter
    def windows(self, windows):
        """Sets the windows of this Order.


        :param windows: The windows of this Order.  # noqa: E501
        :type: list[OrderWindows]
        """

        self._windows = windows

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Order, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Order):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
