# coding: utf-8

"""
    OnRoute API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SolviceRoutingClient
from api.routing_api import RoutingApi  # noqa: E501
from SolviceRoutingClient.rest import ApiException


class TestRoutingApi(unittest.TestCase):
    """RoutingApi unit test stubs"""

    def setUp(self):
        self.api = api.routing_api.RoutingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_solve(self):
        """Test case for solve

        solve a problem  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
