# coding: utf-8

"""
    OnRoute API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SolviceRoutingClient
from api.pvrp_api import PVRPApi  # noqa: E501
from SolviceRoutingClient.rest import ApiException


class TestPVRPApi(unittest.TestCase):
    """PVRPApi unit test stubs"""

    def setUp(self):
        self.api = api.pvrp_api.PVRPApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_solve_pvrp(self):
        """Test case for solve_pvrp

        Solve a PVRP problem  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
