# coding: utf-8

"""
    Solvice API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.options import Options  # noqa: E501
from swagger_client.rest import ApiException


class TestOptions(unittest.TestCase):
    """Options unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptions(self):
        """Test Options"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.options.Options()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
