# coding: utf-8

"""
    OnRoute API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SolviceRoutingClient
from models.visit import Visit  # noqa: E501
from SolviceRoutingClient.rest import ApiException


class TestVisit(unittest.TestCase):
    """Visit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVisit(self):
        """Test Visit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SolviceRoutingClient.models.visit.Visit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
