# coding: utf-8

"""
    OnRoute API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SolviceRoutingClient
from api.solvice_api_api import SolviceAPIApi  # noqa: E501
from SolviceRoutingClient.rest import ApiException


class TestSolviceAPIApi(unittest.TestCase):
    """SolviceAPIApi unit test stubs"""

    def setUp(self):
        self.api = api.solvice_api_api.SolviceAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_job(self):
        """Test case for get_job

        Job  # noqa: E501
        """
        pass

    def test_get_job_status(self):
        """Test case for get_job_status

        Status  # noqa: E501
        """
        pass

    def test_get_solution(self):
        """Test case for get_solution

        Solution  # noqa: E501
        """
        pass

    def test_get_stats(self):
        """Test case for get_stats

        Statistics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
