/* 
 * Solvice API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SolviceRoutingClient.Api;
using SolviceRoutingClient.Model;
using SolviceRoutingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SolviceRoutingClient.Test
{
    /// <summary>
    ///  Class for testing Job
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JobTests
    {
        // TODO uncomment below to declare an instance variable for Job
        //private Job instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Job
            //instance = new Job();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Job
        /// </summary>
        [Test]
        public void JobInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Job
            //Assert.IsInstanceOfType<Job> (instance, "variable 'instance' is a Job");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Solver'
        /// </summary>
        [Test]
        public void SolverTest()
        {
            // TODO unit test for the property 'Solver'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
