/* 
 * Solvice API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SolviceRoutingClient.Api;
using SolviceRoutingClient.Model;
using SolviceRoutingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SolviceRoutingClient.Test
{
    /// <summary>
    ///  Class for testing Options
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OptionsTests
    {
        // TODO uncomment below to declare an instance variable for Options
        //private Options instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Options
            //instance = new Options();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Options
        /// </summary>
        [Test]
        public void OptionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Options
            //Assert.IsInstanceOfType<Options> (instance, "variable 'instance' is a Options");
        }


        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Test]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }
        /// <summary>
        /// Test the property 'AllowOvertime'
        /// </summary>
        [Test]
        public void AllowOvertimeTest()
        {
            // TODO unit test for the property 'AllowOvertime'
        }
        /// <summary>
        /// Test the property 'Overconstrained'
        /// </summary>
        [Test]
        public void OverconstrainedTest()
        {
            // TODO unit test for the property 'Overconstrained'
        }

    }

}
