/* 
 * Solvice API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SolviceRoutingClient.Api;
using SolviceRoutingClient.Model;
using SolviceRoutingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SolviceRoutingClient.Test
{
    /// <summary>
    ///  Class for testing OrderWindows
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderWindowsTests
    {
        // TODO uncomment below to declare an instance variable for OrderWindows
        //private OrderWindows instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderWindows
            //instance = new OrderWindows();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderWindows
        /// </summary>
        [Test]
        public void OrderWindowsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderWindows
            //Assert.IsInstanceOfType<OrderWindows> (instance, "variable 'instance' is a OrderWindows");
        }


        /// <summary>
        /// Test the property 'Starttime'
        /// </summary>
        [Test]
        public void StarttimeTest()
        {
            // TODO unit test for the property 'Starttime'
        }
        /// <summary>
        /// Test the property 'Endtime'
        /// </summary>
        [Test]
        public void EndtimeTest()
        {
            // TODO unit test for the property 'Endtime'
        }
        /// <summary>
        /// Test the property 'Hard'
        /// </summary>
        [Test]
        public void HardTest()
        {
            // TODO unit test for the property 'Hard'
        }

    }

}
