/* 
 * Solvice API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SolviceRoutingClient.Api;
using SolviceRoutingClient.Model;
using SolviceRoutingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SolviceRoutingClient.Test
{
    /// <summary>
    ///  Class for testing Sales
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SalesTests
    {
        // TODO uncomment below to declare an instance variable for Sales
        //private Sales instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Sales
            //instance = new Sales();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Sales
        /// </summary>
        [Test]
        public void SalesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Sales
            //Assert.IsInstanceOfType<Sales> (instance, "variable 'instance' is a Sales");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Home'
        /// </summary>
        [Test]
        public void HomeTest()
        {
            // TODO unit test for the property 'Home'
        }
        /// <summary>
        /// Test the property 'MaxVisits'
        /// </summary>
        [Test]
        public void MaxVisitsTest()
        {
            // TODO unit test for the property 'MaxVisits'
        }
        /// <summary>
        /// Test the property 'MaxTravel'
        /// </summary>
        [Test]
        public void MaxTravelTest()
        {
            // TODO unit test for the property 'MaxTravel'
        }
        /// <summary>
        /// Test the property 'Percentage'
        /// </summary>
        [Test]
        public void PercentageTest()
        {
            // TODO unit test for the property 'Percentage'
        }
        /// <summary>
        /// Test the property 'Languages'
        /// </summary>
        [Test]
        public void LanguagesTest()
        {
            // TODO unit test for the property 'Languages'
        }

    }

}
