/* 
 * Solvice API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SolviceRoutingClient.Api;
using SolviceRoutingClient.Model;
using SolviceRoutingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SolviceRoutingClient.Test
{
    /// <summary>
    ///  Class for testing TMP
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TMPTests
    {
        // TODO uncomment below to declare an instance variable for TMP
        //private TMP instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TMP
            //instance = new TMP();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TMP
        /// </summary>
        [Test]
        public void TMPInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TMP
            //Assert.IsInstanceOfType<TMP> (instance, "variable 'instance' is a TMP");
        }


        /// <summary>
        /// Test the property 'Solver'
        /// </summary>
        [Test]
        public void SolverTest()
        {
            // TODO unit test for the property 'Solver'
        }
        /// <summary>
        /// Test the property 'Sales'
        /// </summary>
        [Test]
        public void SalesTest()
        {
            // TODO unit test for the property 'Sales'
        }
        /// <summary>
        /// Test the property 'Stores'
        /// </summary>
        [Test]
        public void StoresTest()
        {
            // TODO unit test for the property 'Stores'
        }

    }

}
