/* 
 * Solvice API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SolviceRoutingClient.Api;
using SolviceRoutingClient.Model;
using SolviceRoutingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SolviceRoutingClient.Test
{
    /// <summary>
    ///  Class for testing Vehicle
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VehicleTests
    {
        // TODO uncomment below to declare an instance variable for Vehicle
        //private Vehicle instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Vehicle
            //instance = new Vehicle();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Vehicle
        /// </summary>
        [Test]
        public void VehicleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Vehicle
            //Assert.IsInstanceOfType<Vehicle> (instance, "variable 'instance' is a Vehicle");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Startlocation'
        /// </summary>
        [Test]
        public void StartlocationTest()
        {
            // TODO unit test for the property 'Startlocation'
        }
        /// <summary>
        /// Test the property 'Endlocation'
        /// </summary>
        [Test]
        public void EndlocationTest()
        {
            // TODO unit test for the property 'Endlocation'
        }
        /// <summary>
        /// Test the property 'Capacity'
        /// </summary>
        [Test]
        public void CapacityTest()
        {
            // TODO unit test for the property 'Capacity'
        }
        /// <summary>
        /// Test the property 'Capacity2'
        /// </summary>
        [Test]
        public void Capacity2Test()
        {
            // TODO unit test for the property 'Capacity2'
        }
        /// <summary>
        /// Test the property 'Shiftstart'
        /// </summary>
        [Test]
        public void ShiftstartTest()
        {
            // TODO unit test for the property 'Shiftstart'
        }
        /// <summary>
        /// Test the property 'Shiftend'
        /// </summary>
        [Test]
        public void ShiftendTest()
        {
            // TODO unit test for the property 'Shiftend'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
