/* 
 * Solvice API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SolviceRoutingClient.Api;
using SolviceRoutingClient.Model;
using SolviceRoutingClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SolviceRoutingClient.Test
{
    /// <summary>
    ///  Class for testing VRP
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VRPTests
    {
        // TODO uncomment below to declare an instance variable for VRP
        //private VRP instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of VRP
            //instance = new VRP();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of VRP
        /// </summary>
        [Test]
        public void VRPInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VRP
            //Assert.IsInstanceOfType<VRP> (instance, "variable 'instance' is a VRP");
        }


        /// <summary>
        /// Test the property 'Solver'
        /// </summary>
        [Test]
        public void SolverTest()
        {
            // TODO unit test for the property 'Solver'
        }
        /// <summary>
        /// Test the property 'Locations'
        /// </summary>
        [Test]
        public void LocationsTest()
        {
            // TODO unit test for the property 'Locations'
        }
        /// <summary>
        /// Test the property 'Fleet'
        /// </summary>
        [Test]
        public void FleetTest()
        {
            // TODO unit test for the property 'Fleet'
        }
        /// <summary>
        /// Test the property 'Orders'
        /// </summary>
        [Test]
        public void OrdersTest()
        {
            // TODO unit test for the property 'Orders'
        }

    }

}
