/*
 * OnRoute API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.solvice.routing.api.client.api;

import io.solvice.routing.api.client.ApiException;
import io.solvice.routing.api.client.model.InputError;
import io.solvice.routing.api.client.model.Job;
import io.solvice.routing.api.client.model.PVRP;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PvrpApi
 */
@Ignore
public class PvrpApiTest {

    private final PvrpApi api = new PvrpApi();

    /**
     * Solve a PVRP problem
     *
     * Periodic vehicle routing problems
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void solvePVRPTest() throws ApiException {
        PVRP body = null;
        Job response = api.solvePVRP(body);

        // TODO: test validations
    }
}
