/*
 * OnRoute API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.solvice.routing.api.client.api;

import io.solvice.routing.api.client.ApiException;
import io.solvice.routing.api.client.model.Job;
import io.solvice.routing.api.client.model.Stats;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SolviceApiApi
 */
@Ignore
public class SolviceApiApiTest {

    private final SolviceApiApi api = new SolviceApiApi();

    /**
     * Job
     *
     * When posting a new solve request, this job can be checked again under this endpoint. In fact, it should be the entire request posted as-is.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getJobTest() throws ApiException {
        UUID jobId = null;
        Job response = api.getJob(jobId);

        // TODO: test validations
    }
    /**
     * Status
     *
     * Retrieve a specific job status
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getJobStatusTest() throws ApiException {
        String jobId = null;
        Job response = api.getJobStatus(jobId);

        // TODO: test validations
    }
    /**
     * Solution
     *
     * Returns the actual solution of the job. Only present when the status is &#x60;SOLVED&#x60;.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSolutionTest() throws ApiException {
        UUID jobId = null;
        Job response = api.getSolution(jobId);

        // TODO: test validations
    }
    /**
     * Statistics
     *
     * Returns the information on why a job has been solved the way it&#x27;s been. Information includes specific unresolved objects. Want to know how it is optimised? This endpoint lets you know what rules have been overruled. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatsTest() throws ApiException {
        UUID jobId = null;
        Stats response = api.getStats(jobId);

        // TODO: test validations
    }
}
