/*
 * OnRoute API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.solvice.routing.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * OrderWindows
 */

public class OrderWindows {

  @SerializedName("starttime")
  private Integer starttime = null;

  @SerializedName("endtime")
  private Integer endtime = null;

  @SerializedName("hard")
  private Boolean hard = null;
  public OrderWindows starttime(Integer starttime) {
    this.starttime = starttime;
    return this;
  }

  

  /**
  * Get starttime
  * minimum: 0
  * maximum: 1439
  * @return starttime
  **/
  @Schema(example = "530", description = "")
  public Integer getStarttime() {
    return starttime;
  }
  public void setStarttime(Integer starttime) {
    this.starttime = starttime;
  }
  public OrderWindows endtime(Integer endtime) {
    this.endtime = endtime;
    return this;
  }

  

  /**
  * Get endtime
  * minimum: 0
  * maximum: 1439
  * @return endtime
  **/
  @Schema(example = "550", description = "")
  public Integer getEndtime() {
    return endtime;
  }
  public void setEndtime(Integer endtime) {
    this.endtime = endtime;
  }
  public OrderWindows hard(Boolean hard) {
    this.hard = hard;
    return this;
  }

  

  /**
  * Get hard
  * @return hard
  **/
  @Schema(description = "")
  public Boolean isHard() {
    return hard;
  }
  public void setHard(Boolean hard) {
    this.hard = hard;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderWindows orderWindows = (OrderWindows) o;
    return Objects.equals(this.starttime, orderWindows.starttime) &&
        Objects.equals(this.endtime, orderWindows.endtime) &&
        Objects.equals(this.hard, orderWindows.hard);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(starttime, endtime, hard);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderWindows {\n");
    
    sb.append("    starttime: ").append(toIndentedString(starttime)).append("\n");
    sb.append("    endtime: ").append(toIndentedString(endtime)).append("\n");
    sb.append("    hard: ").append(toIndentedString(hard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
