/*
 * OnRoute API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.solvice.routing.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * Define the planning period.
 */
@Schema(description = "Define the planning period.")
public class PVRPPeriod {

  @SerializedName("start")
  private LocalDate start = null;

  @SerializedName("end")
  private LocalDate end = null;
  public PVRPPeriod start(LocalDate start) {
    this.start = start;
    return this;
  }

  

  /**
  * Start date of the planning period.
  * @return start
  **/
  @Schema(description = "Start date of the planning period.")
  public LocalDate getStart() {
    return start;
  }
  public void setStart(LocalDate start) {
    this.start = start;
  }
  public PVRPPeriod end(LocalDate end) {
    this.end = end;
    return this;
  }

  

  /**
  * End date of the planning period. Not inclusive.
  * @return end
  **/
  @Schema(description = "End date of the planning period. Not inclusive.")
  public LocalDate getEnd() {
    return end;
  }
  public void setEnd(LocalDate end) {
    this.end = end;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PVRPPeriod pvRPPeriod = (PVRPPeriod) o;
    return Objects.equals(this.start, pvRPPeriod.start) &&
        Objects.equals(this.end, pvRPPeriod.end);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(start, end);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PVRPPeriod {\n");
    
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
