/*
 * OnRoute API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.solvice.routing.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.solvice.routing.api.client.model.Location;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Sales
 */

public class Sales {

  @SerializedName("name")
  private String name = null;

  @SerializedName("home")
  private Location home = null;

  @SerializedName("max_visits")
  private Integer maxVisits = null;

  @SerializedName("max_travel")
  private Integer maxTravel = null;

  @SerializedName("percentage")
  private Integer percentage = null;

  @SerializedName("languages")
  private List<String> languages = null;
  public Sales name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  @Schema(example = "sales1", required = true, description = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public Sales home(Location home) {
    this.home = home;
    return this;
  }

  

  /**
  * Get home
  * @return home
  **/
  @Schema(required = true, description = "")
  public Location getHome() {
    return home;
  }
  public void setHome(Location home) {
    this.home = home;
  }
  public Sales maxVisits(Integer maxVisits) {
    this.maxVisits = maxVisits;
    return this;
  }

  

  /**
  * Maximum number of total visits
  * @return maxVisits
  **/
  @Schema(example = "5", description = "Maximum number of total visits")
  public Integer getMaxVisits() {
    return maxVisits;
  }
  public void setMaxVisits(Integer maxVisits) {
    this.maxVisits = maxVisits;
  }
  public Sales maxTravel(Integer maxTravel) {
    this.maxTravel = maxTravel;
    return this;
  }

  

  /**
  * Maximum total travel time (in km bird distance)
  * @return maxTravel
  **/
  @Schema(example = "1000", description = "Maximum total travel time (in km bird distance)")
  public Integer getMaxTravel() {
    return maxTravel;
  }
  public void setMaxTravel(Integer maxTravel) {
    this.maxTravel = maxTravel;
  }
  public Sales percentage(Integer percentage) {
    this.percentage = percentage;
    return this;
  }

  

  /**
  * Working percentage (parttime)
  * @return percentage
  **/
  @Schema(example = "100", description = "Working percentage (parttime)")
  public Integer getPercentage() {
    return percentage;
  }
  public void setPercentage(Integer percentage) {
    this.percentage = percentage;
  }
  public Sales languages(List<String> languages) {
    this.languages = languages;
    return this;
  }

  public Sales addLanguagesItem(String languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<String>();
    }
    this.languages.add(languagesItem);
    return this;
  }

  /**
  * Languages
  * @return languages
  **/
  @Schema(description = "Languages")
  public List<String> getLanguages() {
    return languages;
  }
  public void setLanguages(List<String> languages) {
    this.languages = languages;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sales sales = (Sales) o;
    return Objects.equals(this.name, sales.name) &&
        Objects.equals(this.home, sales.home) &&
        Objects.equals(this.maxVisits, sales.maxVisits) &&
        Objects.equals(this.maxTravel, sales.maxTravel) &&
        Objects.equals(this.percentage, sales.percentage) &&
        Objects.equals(this.languages, sales.languages);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(name, home, maxVisits, maxTravel, percentage, languages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sales {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    home: ").append(toIndentedString(home)).append("\n");
    sb.append("    maxVisits: ").append(toIndentedString(maxVisits)).append("\n");
    sb.append("    maxTravel: ").append(toIndentedString(maxTravel)).append("\n");
    sb.append("    percentage: ").append(toIndentedString(percentage)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
