/*
 * OnRoute API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.solvice.routing.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.solvice.routing.api.client.model.StatsGoals;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Stats
 */

public class Stats {

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("goals")
  private List<StatsGoals> goals = null;
  public Stats id(UUID id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  @Schema(example = "d290f1ee-6c54-4b01-90e6-d701748f0851", description = "")
  public UUID getId() {
    return id;
  }
  public void setId(UUID id) {
    this.id = id;
  }
  public Stats goals(List<StatsGoals> goals) {
    this.goals = goals;
    return this;
  }

  public Stats addGoalsItem(StatsGoals goalsItem) {
    if (this.goals == null) {
      this.goals = new ArrayList<StatsGoals>();
    }
    this.goals.add(goalsItem);
    return this;
  }

  /**
  * Get goals
  * @return goals
  **/
  @Schema(description = "")
  public List<StatsGoals> getGoals() {
    return goals;
  }
  public void setGoals(List<StatsGoals> goals) {
    this.goals = goals;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Stats stats = (Stats) o;
    return Objects.equals(this.id, stats.id) &&
        Objects.equals(this.goals, stats.goals);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, goals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Stats {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    goals: ").append(toIndentedString(goals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
