/*
 * OnRoute API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.solvice.routing.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.solvice.routing.api.client.model.StatsConflicts;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * StatsGoals
 */

public class StatsGoals {

  @SerializedName("goal")
  private String goal = null;

  @SerializedName("weight")
  private Integer weight = null;

  @SerializedName("conflicts")
  private List<StatsConflicts> conflicts = null;
  public StatsGoals goal(String goal) {
    this.goal = goal;
    return this;
  }

  

  /**
  * Get goal
  * @return goal
  **/
  @Schema(description = "")
  public String getGoal() {
    return goal;
  }
  public void setGoal(String goal) {
    this.goal = goal;
  }
  public StatsGoals weight(Integer weight) {
    this.weight = weight;
    return this;
  }

  

  /**
  * Get weight
  * @return weight
  **/
  @Schema(description = "")
  public Integer getWeight() {
    return weight;
  }
  public void setWeight(Integer weight) {
    this.weight = weight;
  }
  public StatsGoals conflicts(List<StatsConflicts> conflicts) {
    this.conflicts = conflicts;
    return this;
  }

  public StatsGoals addConflictsItem(StatsConflicts conflictsItem) {
    if (this.conflicts == null) {
      this.conflicts = new ArrayList<StatsConflicts>();
    }
    this.conflicts.add(conflictsItem);
    return this;
  }

  /**
  * Get conflicts
  * @return conflicts
  **/
  @Schema(description = "")
  public List<StatsConflicts> getConflicts() {
    return conflicts;
  }
  public void setConflicts(List<StatsConflicts> conflicts) {
    this.conflicts = conflicts;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatsGoals statsGoals = (StatsGoals) o;
    return Objects.equals(this.goal, statsGoals.goal) &&
        Objects.equals(this.weight, statsGoals.weight) &&
        Objects.equals(this.conflicts, statsGoals.conflicts);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(goal, weight, conflicts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatsGoals {\n");
    
    sb.append("    goal: ").append(toIndentedString(goal)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    conflicts: ").append(toIndentedString(conflicts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
