/*
 * OnRoute API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.solvice.routing.api.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.solvice.routing.api.client.model.Sales;
import io.solvice.routing.api.client.model.Store;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * TMP
 */

public class TMP {

  @SerializedName("solver")
  private String solver = null;

  @SerializedName("sales")
  private List<Sales> sales = new ArrayList<Sales>();

  @SerializedName("stores")
  private List<Store> stores = new ArrayList<Store>();
  public TMP solver(String solver) {
    this.solver = solver;
    return this;
  }

  

  /**
  * Get solver
  * @return solver
  **/
  @Schema(example = "TMP", required = true, description = "")
  public String getSolver() {
    return solver;
  }
  public void setSolver(String solver) {
    this.solver = solver;
  }
  public TMP sales(List<Sales> sales) {
    this.sales = sales;
    return this;
  }

  public TMP addSalesItem(Sales salesItem) {
    this.sales.add(salesItem);
    return this;
  }

  /**
  * Get sales
  * @return sales
  **/
  @Schema(required = true, description = "")
  public List<Sales> getSales() {
    return sales;
  }
  public void setSales(List<Sales> sales) {
    this.sales = sales;
  }
  public TMP stores(List<Store> stores) {
    this.stores = stores;
    return this;
  }

  public TMP addStoresItem(Store storesItem) {
    this.stores.add(storesItem);
    return this;
  }

  /**
  * Get stores
  * @return stores
  **/
  @Schema(required = true, description = "")
  public List<Store> getStores() {
    return stores;
  }
  public void setStores(List<Store> stores) {
    this.stores = stores;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TMP TMP = (TMP) o;
    return Objects.equals(this.solver, TMP.solver) &&
        Objects.equals(this.sales, TMP.sales) &&
        Objects.equals(this.stores, TMP.stores);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(solver, sales, stores);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TMP {\n");
    
    sb.append("    solver: ").append(toIndentedString(solver)).append("\n");
    sb.append("    sales: ").append(toIndentedString(sales)).append("\n");
    sb.append("    stores: ").append(toIndentedString(stores)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
