# coding: utf-8

"""
    OnRoute API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class OrderWindows(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'starttime': 'int',
        'endtime': 'int',
        'hard': 'bool'
    }

    attribute_map = {
        'starttime': 'starttime',
        'endtime': 'endtime',
        'hard': 'hard'
    }

    def __init__(self, starttime=None, endtime=None, hard=None):  # noqa: E501
        """OrderWindows - a model defined in Swagger"""  # noqa: E501
        self._starttime = None
        self._endtime = None
        self._hard = None
        self.discriminator = None
        if starttime is not None:
            self.starttime = starttime
        if endtime is not None:
            self.endtime = endtime
        if hard is not None:
            self.hard = hard

    @property
    def starttime(self):
        """Gets the starttime of this OrderWindows.  # noqa: E501


        :return: The starttime of this OrderWindows.  # noqa: E501
        :rtype: int
        """
        return self._starttime

    @starttime.setter
    def starttime(self, starttime):
        """Sets the starttime of this OrderWindows.


        :param starttime: The starttime of this OrderWindows.  # noqa: E501
        :type: int
        """

        self._starttime = starttime

    @property
    def endtime(self):
        """Gets the endtime of this OrderWindows.  # noqa: E501


        :return: The endtime of this OrderWindows.  # noqa: E501
        :rtype: int
        """
        return self._endtime

    @endtime.setter
    def endtime(self, endtime):
        """Sets the endtime of this OrderWindows.


        :param endtime: The endtime of this OrderWindows.  # noqa: E501
        :type: int
        """

        self._endtime = endtime

    @property
    def hard(self):
        """Gets the hard of this OrderWindows.  # noqa: E501


        :return: The hard of this OrderWindows.  # noqa: E501
        :rtype: bool
        """
        return self._hard

    @hard.setter
    def hard(self, hard):
        """Sets the hard of this OrderWindows.


        :param hard: The hard of this OrderWindows.  # noqa: E501
        :type: bool
        """

        self._hard = hard

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrderWindows, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderWindows):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
