# coding: utf-8

"""
    OnRoute API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from SolviceRoutingClient.models.solver import Solver  # noqa: F401,E501


class SolveRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hook': 'str',
        'solver': 'Solver'
    }

    attribute_map = {
        'hook': 'hook',
        'solver': 'solver'
    }

    def __init__(self, hook=None, solver=None):  # noqa: E501
        """SolveRequest - a model defined in Swagger"""  # noqa: E501
        self._hook = None
        self._solver = None
        self.discriminator = None
        if hook is not None:
            self.hook = hook
        self.solver = solver

    @property
    def hook(self):
        """Gets the hook of this SolveRequest.  # noqa: E501

        Webhook endpoint to receive POST request with the id.  # noqa: E501

        :return: The hook of this SolveRequest.  # noqa: E501
        :rtype: str
        """
        return self._hook

    @hook.setter
    def hook(self, hook):
        """Sets the hook of this SolveRequest.

        Webhook endpoint to receive POST request with the id.  # noqa: E501

        :param hook: The hook of this SolveRequest.  # noqa: E501
        :type: str
        """

        self._hook = hook

    @property
    def solver(self):
        """Gets the solver of this SolveRequest.  # noqa: E501


        :return: The solver of this SolveRequest.  # noqa: E501
        :rtype: Solver
        """
        return self._solver

    @solver.setter
    def solver(self, solver):
        """Sets the solver of this SolveRequest.


        :param solver: The solver of this SolveRequest.  # noqa: E501
        :type: Solver
        """
        if solver is None:
            raise ValueError("Invalid value for `solver`, must not be `None`")  # noqa: E501

        self._solver = solver

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SolveRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SolveRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
