# coding: utf-8

"""
    OnRoute API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from SolviceRoutingClient.models.location import Location  # noqa: F401,E501


class Store(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'location': 'Location',
        'frequency': 'int',
        'potential': 'int',
        'language': 'str',
        'duration': 'int'
    }

    attribute_map = {
        'name': 'name',
        'location': 'location',
        'frequency': 'frequency',
        'potential': 'potential',
        'language': 'language',
        'duration': 'duration'
    }

    def __init__(self, name=None, location=None, frequency=None, potential=None, language=None, duration=None):  # noqa: E501
        """Store - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._location = None
        self._frequency = None
        self._potential = None
        self._language = None
        self._duration = None
        self.discriminator = None
        self.name = name
        self.location = location
        if frequency is not None:
            self.frequency = frequency
        if potential is not None:
            self.potential = potential
        if language is not None:
            self.language = language
        if duration is not None:
            self.duration = duration

    @property
    def name(self):
        """Gets the name of this Store.  # noqa: E501


        :return: The name of this Store.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Store.


        :param name: The name of this Store.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def location(self):
        """Gets the location of this Store.  # noqa: E501


        :return: The location of this Store.  # noqa: E501
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this Store.


        :param location: The location of this Store.  # noqa: E501
        :type: Location
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501

        self._location = location

    @property
    def frequency(self):
        """Gets the frequency of this Store.  # noqa: E501

        Visit frequency  # noqa: E501

        :return: The frequency of this Store.  # noqa: E501
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this Store.

        Visit frequency  # noqa: E501

        :param frequency: The frequency of this Store.  # noqa: E501
        :type: int
        """

        self._frequency = frequency

    @property
    def potential(self):
        """Gets the potential of this Store.  # noqa: E501


        :return: The potential of this Store.  # noqa: E501
        :rtype: int
        """
        return self._potential

    @potential.setter
    def potential(self, potential):
        """Sets the potential of this Store.


        :param potential: The potential of this Store.  # noqa: E501
        :type: int
        """

        self._potential = potential

    @property
    def language(self):
        """Gets the language of this Store.  # noqa: E501


        :return: The language of this Store.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this Store.


        :param language: The language of this Store.  # noqa: E501
        :type: str
        """

        self._language = language

    @property
    def duration(self):
        """Gets the duration of this Store.  # noqa: E501


        :return: The duration of this Store.  # noqa: E501
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this Store.


        :param duration: The duration of this Store.  # noqa: E501
        :type: int
        """

        self._duration = duration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Store, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Store):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
